ODA/ODA/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('welcome.urls')),
    path('home/',include('patient_home.urls')),
    path('pharma/', include('Registration.urls')),
    path('pharma/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('Password-Reset/', auth_views.PasswordResetView.as_view(template_name='welcome/password_reset.html'),
         name='password_reset'),
    path('Password-Reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='welcome/password_reset_done.html'),
         name='password_reset_done'),
    path('Password-Reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='welcome/password_reset_con.html'),
         name='password_reset_confirm'),
    path('Password-Reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='welcome/pass_reset_complete.html'),
         name='password_reset_complete'),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ODA/blog/urls.py
from django.urls import path
from blog import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'blog'

urlpatterns = [
    path('', views.home, name='blog_home'),
    path('make/', views.make, name='make_blog'),
    path('edit/<int:post_id>', views.edit, name='edit_blog'),
    path('delete/<int:post_id>', views.de1, name='delete_blog'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ODA/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from welcome.models import Doctors

# patients database

# class Patient_DB(models.Model):
#     P_Id = models.OneToOneField(User, on_delete=models.CASCADE)
#     Age = models.IntegerField()
#     Gender = models.CharField(max_length=10)
#     Blood_group = models.CharField(max_length=3)
#     Marital_Status = models.CharField(max_length=3)
#     Phone_num = models.IntegerField()
#     Emergency_num = models.IntegerField()
#
#
# class Hospital_Details(models.Model):
#     H_Id = models.OneToOneField(User, on_delete=models.CASCADE)
#     H_Name = models.CharField(max_length=100)
#     Address = models.CharField(max_length=250)
#     Phone1 = models.IntegerField()
#     Phone2 = models.IntegerField()
#     Phone3 = models.IntegerField()
#
#
# class Doctor_Type(models.Model):
#     T_Id = models.CharField(max_length=100)
#     Spec = models.CharField(max_length=250)
#
#
# class Doctors(models.Model):
#     D_Id = models.OneToOneField(User, on_delete=models.CASCADE)
#     H_Id = models.ForeignKey(Hospital_Details, on_delete=models.PROTECT)
#     T_Id = models.ForeignKey(Doctor_Type, on_delete=models.PROTECT)
#     Avail = models.BooleanField(blank=True)
#     Phone = models.IntegerField(blank=True, default=0)
#     Degrees = models.CharField(max_length=250, blank=True)
#     Latitudes = models.IntegerField(blank=True, default=0)
#     Longitudes = models.IntegerField(blank=True, default=0)
#     Desc = models.TextField(blank=True)


class textinblog(models.Model):
    doctors = models.ForeignKey(Doctors, on_delete=models.PROTECT)
    the_text = models.TextField()
    the_sub = models.CharField(default='None', null=True, max_length=150)
    picture = models.ImageField(upload_to='blog/%Y/%m/%d', default='None.png', blank=True)

    # def __str__(self):
    #     return self.the_text

#
# class Tips(models.Model):
#     tip = models.TextField()
#
#
# class Medical_shop(models.Model):
#     shop_id = models.CharField(max_length=255, primary_key=True)
#     shop_name = models.CharField(max_length=255)
#     Lattitude = models.FloatField(default='NULL')
#     Longitude = models.FloatField(default='NULL')
#
#
# class Stock_availability(models.Model):
#     shop_id = models.ForeignKey(Medical_shop, on_delete=models.PROTECT)
#     Med_id = models.CharField(max_length=255)
#     Medicine_name = models.CharField(max_length=255)
#     Stock = models.IntegerField()
#
#
# class General_Medicine(models.Model):
#     Disease = models.CharField(max_length=255, primary_key=True)
#     Medicine = models.CharField(max_length=255)
#
#
# class Blood_Bank(models.Model):
#     BB_id = models.CharField(max_length=255, primary_key=True)
#     BB_name = models.CharField(max_length=255)
#     Lat = models.FloatField(default='NULL')
#     Long = models.FloatField(default='NULL')
#
#
# class Blood_avail(models.Model):
#     BB_id = models.ForeignKey(Blood_Bank, on_delete=models.PROTECT)
#     Blood_grp = models.CharField(max_length=255)
#     Availability = models.CharField(max_length=255)

ODA/blog/forms.py
from django import forms
from blog.models import textinblog


class Bloginput(forms.ModelForm):
    # the_text = forms.Textarea()
    # the_sub = forms.CharField(max_length=150)
    # picture = forms.ImageField()
    class Meta:
        model = textinblog
        fields = ['the_text', 'the_sub', 'picture']

ODA/blog/views.py
from django.shortcuts import render, redirect
from blog.forms import Bloginput
from blog.models import textinblog, Doctors
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    spec = Doctors.objects.get(D_Id=request.user).Spec.split()
    author = Doctors.objects.get(D_Id=request.user).D_Id
    return render(request, 'blog/blogpage.html', {'posts': textinblog.objects.all(), 'spec': spec, 'author': author})


@login_required
def make(request):
    if request.method == 'POST':
        blotext = Bloginput(request.POST, request.FILES)

        if blotext.is_valid():
            subj = blotext.cleaned_data['the_sub']
            blotext.save(commit=False)
            user = Doctors.objects.get(D_Id=request.user)
            text = blotext.cleaned_data['the_text']
            picture = blotext.cleaned_data['picture']
            b = textinblog(doctors=user, the_text=text, the_sub=subj, picture=picture)
            b.save()
            return redirect('blog:blog_home')
    else:
        blotext = Bloginput()
        return render(request, 'blog/make.html', {'form': blotext})


def edit(request, post_id):
    textinblog.objects.get(id=post_id).delete()
    if request.method == 'POST':
        blotext = Bloginput(request.POST, request.FILES)
        if blotext.is_valid():
            subj = blotext.cleaned_data['the_sub']
            blotext.save(commit=False)
            user = Doctors.objects.get(D_Id=request.user)
            text = blotext.cleaned_data['the_text']
            picture = blotext.cleaned_data['picture']
            b = textinblog(doctors=user, the_text=text, the_sub=subj, picture=picture)
            b.save()
            return redirect('blog:blog_home')
    else:
        blotext = Bloginput()
    return render(request, 'blog/make.html', {'form': blotext})


def de1(request, post_id):
    textinblog.objects.get(id=post_id).delete()
    return redirect('blog:blog_home')

ODA/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
            {{ title }}
        {% else %}
            blog
        {% endif %}
    </title>
<style>
.blog_sub{
    border: 1px solid green;
    width: 75%;
    background: greenyellow;
    padding: 5px;
    border-radius: 0 4px 4px 0;
}
.blog_post{
    border: 1px solid blue;
    width: 75%;
    background: blue;
    padding: 5px;
    border-radius: 0 4px 4px 0;
}

.blog_author{
    border: 1px solid red;
    width: 10%;
    margin-right: 10%;
    background: red;
    padding: 1px;
    border-radius: 0 4px 4px 0;
}

.blog_message{
    border: 1px lawngreen;
    padding: 1px;
    text-decoration-color: aliceblue;
    text-align: center;
}
</style>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

ODA/blog/templates/blog/blogpage.html
{% extends 'welcome/base.html' %}

{% block content %}
    <br><br><br><br>
    <div class="container">
            <div class="blog_message">{{ mmm }}</div>
            {% if posts %}
                {% for post in posts %}
                    <div class="row" style="border: 2px solid #2bb673; border-radius: 7px;border-spacing: 15px;height: 20%">
                        {% if spec == post.doctors.Spec.split %}
                            <div class="col col-sm-2  blog_sub">
                                {{ post.the_sub }}
                            </div>
                            <div class="col col-sm-1">
                                {% if post.picture.url != '/media/None.png' %}
                                    <br>
                                    <img src="{{ post.picture.url }}" style="display:block;width: 100%;height: auto ;border: 2px solid #2bb673; border-radius: 7px;">
                                    <br>
                                {% endif %}
                            </div>
                            <div class="blog_post col col-sm-8" >
                                {{ post.the_text }}
                            </div>

                            <div class="blog_author col col-sm-1">{{ post.doctors.D_Id }}
                                {% if post.doctors.D_Id == author %}
                                    <a href="{% url 'blog:edit_blog' post.id %}">Edit</a>
                                    <a href="{% url 'blog:delete_blog' post.id%}">Delete</a>
                                {% endif %}
                                <br><br>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
              {% endif %}
                <br><br><br>
              {% for post in posts %}
                  <div class="row" style="border: 2px solid #2bb673; border-radius: 7px;border-spacing: 15px;outline: 10px;height: 20%">
                    {% if spec != post.doctors.Spec.split %}
                      <div class="col col-sm-2  blog_sub">
                          {{ post.the_sub }}
                      </div>
                      <div class="col col-sm-1">
                          {% if post.picture.url != '/media/None.png' %}
                            <br>
                            <img src="{{ post.picture.url }}" style="display:block;width: 100%;height: auto ;border: 2px solid #2bb673; border-radius: 7px;">
                            <br>
                          {% endif %}
                        </div>
                      <div class="blog_post col col-sm-8">
                        {{ post.the_text }}
                      </div>
                      <div class="blog_author col col-sm-1">{{ post.doctors.D_Id }}
                      {% if post.doctors.D_Id == author %}
                        <a href="{% url 'blog:edit_blog'  post.id %}">Edit</a>
                        <a href="{% url 'blog:delete_blog' post.id %}">Delete</a>
                      {% endif %}
                      <br><br><br>
                      </div>
                    {% endif %}
                  </div>
              {% endfor %}
                <br><br>
                <div class="row">
                    <a href="{% url 'blog:make_blog' %}">Add Blog</a>
                </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

ODA/blog/templates/blog/make.html
{% extends 'welcome/base.html' %}

{% block content %}
    <br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST" action="{% url 'blog:make_blog' %}" enctype="multipart/form-data" class="form-control">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary btn-lg" type="submit">Post this Bad Boy</button>
                </form>
            </div>
        </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}