ODA/ODA/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('welcome.urls')),
    path('home/',include('patient_home.urls')),
    path('pharma/', include('Registration.urls')),
    path('pharma/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('Password-Reset/', auth_views.PasswordResetView.as_view(template_name='welcome/password_reset.html'),
         name='password_reset'),
    path('Password-Reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='welcome/password_reset_done.html'),
         name='password_reset_done'),
    path('Password-Reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='welcome/password_reset_con.html'),
         name='password_reset_confirm'),
    path('Password-Reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='welcome/pass_reset_complete.html'),
         name='password_reset_complete'),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ODA/Registration/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from Registration import views
app_name = 'Registration'

urlpatterns = [
    # path('',TemplateView.as_view(template_name='Registration/home.html'), name='pharmacies'),
    path('',views.homepage, name='pharmacies'),
    path('signup/', views.register, name='signup'),
    path('userlogin/',views.userlogin,name='userlogin'),
    path('userlogout/',views.userlogout,name='userlogout'),
    #path('data/', views.data, name="data"),
    path('upload/',views.upload, name='upload'),
    #path('data1/',views.data1 , name='data1'),
    path('reset/',views.reset,name='reset'),
]

ODA/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}login{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

ODA/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <b>Welcome Mr.{{ user.username }}!</b>
  <p>
      <b>Welcome to Med_Shop page !!!</b>
      <br><br>
      <a href="{% url 'Registration:userlogout' %}">logout</a>
      <br>
      <p><a href="{% url 'password_reset' %}">reset password</a></p>
        <br><br>
      <a href="{% url 'Registration:data' %}">ADD SHOP</a>
  </p>
{% else %}
  <p>You are not logged in.Please click below.</p>
    <a href="{% url 'Registration:userlogin' %}">Login</a><br><br><i><b>OR</b></i>
    <br><br>
    <a href="{% url 'Registration:signup' %}">Signup</a>
{% endif %}
{% endblock %}

ODA/templates/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>
    <form method="post" action="{% url 'Registration:userlogin' %}">
    {% csrf_token %}
        <label>username:
        <input type="text" required name="username">
            </label>
        <label>
            password:
            <input type="password" required name="password">
        </label>
        <button type="submit">Login</button><br>
         <p><a href="{% url 'password_reset' %}">Forgot password ?</a></p>
        <br><br>


    </form>
{% endblock %}

ODA/templates/med_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ODA/templates/shop_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>data form</title>
</head>
<body>

<form action="{% url 'Registration:data1' %}" method="post">
    {%  csrf_token %}

    <h>
        <b>SHOP DATA</b>
    </h>

    <br><br>

    Shopid:<br>
    <input type="number" name="sid" id="sid" required>

    <br>

    shopname:<br>
    <input type="text" name="sname" id="sname" required>

    <br>

    lattitude:<br>
    <input type="number" name="lati" id="lati" required>

    <br>

    longitude:<br>
    <input type="number" name="longi" id="longi" required>

    <br><br>

    <button type="submit">Submit</button>

    <br><br>

    <a href="{% url 'Registration:upload' %}">Add Stock</a>
<!--    <h><b>STOCK DATA</b></h><br><br>
    shopid:<br>
    <input type="number" name="shopid id" id="shopid"><br>
    med id:<br>
    <input type="number" name="med id" id="med id"><br>
    med name:<br>
    <input type="text" name="med name" id="med name"><br>
    stock:<br>
    <input type="number" name="stock" id="stock"><br><br>
-->
</form>

</body>
</html>

ODA/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
      {% if registered %}
        <h1> Registered Successfully </h1>
      {% else %}
        <h2>Sign up</h2>
        <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            <button type="submit">Sign up</button>
        </form>
      {% endif %}
{% endblock %}

ODA/templates/upload.html
<html>
    <head>
        <title>
            UPLOAD Excel
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">

        <form action="{% url "Registration:upload" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p><b>Upload Stock data through Excel file</b></p>
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   required="required">
            </input><br><br>
            <input type="submit"
                   value="Upload">
            </input>
        </form>
        <hr>
    </body>
</html>