ODA/ODA/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('welcome.urls')),
    path('home/',include('patient_home.urls')),
    path('pharma/', include('Registration.urls')),
    path('pharma/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('Password-Reset/', auth_views.PasswordResetView.as_view(template_name='welcome/password_reset.html'),
         name='password_reset'),
    path('Password-Reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='welcome/password_reset_done.html'),
         name='password_reset_done'),
    path('Password-Reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='welcome/password_reset_con.html'),
         name='password_reset_confirm'),
    path('Password-Reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='welcome/pass_reset_complete.html'),
         name='password_reset_complete'),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ODA/Registration/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from Registration import views
app_name = 'Registration'

urlpatterns = [
    # path('',TemplateView.as_view(template_name='Registration/home.html'), name='pharmacies'),
    path('',views.homepage, name='pharmacies'),
    path('signup/', views.register, name='signup'),
    path('userlogin/',views.userlogin,name='userlogin'),
    path('userlogout/',views.userlogout,name='userlogout'),
    #path('data/', views.data, name="data"),
    path('upload/',views.upload, name='upload'),
    #path('data1/',views.data1 , name='data1'),
    path('reset/',views.reset,name='reset'),
]

ODA/blog/urls.py
from django.urls import path
from blog import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'blog'

urlpatterns = [
    path('', views.home, name='blog_home'),
    path('make/', views.make, name='make_blog'),
    path('edit/<int:post_id>', views.edit, name='edit_blog'),
    path('delete/<int:post_id>', views.de1, name='delete_blog'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ODA/welcome/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
# from patient_home import views

app_name = 'welcome'

urlpatterns = [
    path('doc_home/', views.home, name='home'),
    path('', views.front_page, name='frontpage'),
    path('logout/', auth_views.LogoutView.as_view(template_name='welcome/home.html'), name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
    path('doctor/', views.doctor_page, name='doc-l-r'),
    path('doc_login/', views.doc_login, name='doc-login'),
    path('doc_register/', views.doc_register, name='doc-register'),
    path('user_register/', views.pat_log, name='pat_log'),
    path('Profile_update/', views.pro_upd_doc, name='profile-update'),
    path('doc_home/Schedule_manager/', views.schedule, name='schedule'),
]

ODA/welcome/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Patient_DB(models.Model):
    P_Id = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    Age = models.CharField(max_length=3)
    emerg_email = models.CharField(max_length=50,blank=True)
    Gender = models.CharField(max_length=10)
    Blood_group = models.CharField(max_length=5)                                ##changed the max value
    medical_con = models.CharField(max_length=300, default='None')
    image_url = models.CharField(max_length=400, default='')
    user_pat = models.CharField(max_length=4 ,default='no') #############
    Phone_num = models.CharField(max_length=10,blank=True)
    Emergency_num = models.CharField(max_length=50,blank=True)



class Hospital_Details(models.Model):

    H_Id = models.OneToOneField(User, on_delete=models.CASCADE)
    H_Name = models.CharField(max_length=100)
    Address = models.CharField(max_length=250)
    Phone1 = models.IntegerField(null=True)

class Doctors(models.Model):

    D_Id = models.OneToOneField(User, on_delete=models.CASCADE ,primary_key=True)
    H_Id = models.ForeignKey(Hospital_Details, on_delete=models.PROTECT, null=True)
    Avail = models.BooleanField(blank=True ,default=True )
    Phone = models.CharField(max_length=10,blank=True)
    gender = models.CharField(max_length=10, default='Male', blank=True)
    user_pat = models.CharField(max_length=4, default='no') ##############
    Degrees = models.CharField(max_length=250, blank=True)
    doc_type = models.CharField(max_length=250, blank=True)
    license = models.CharField(max_length=10,blank=True)
    Latitudes = models.FloatField(max_length=30, blank=True, default=0)
    Longitudes = models.FloatField(max_length=30, blank=True, default=0)
    d_website = models.CharField(max_length=30, blank=True)
    Desc = models.TextField(blank=True)
    doc_info=models.TextField(blank=True,default="Edit your info in Profile Manager")
    About_Clinic = models.TextField(max_length=300,blank=True,default="Its good")
    Other_info = models.TextField(max_length=300, blank=True, default="Its great")
    Spec = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return f'{self.D_Id.username}'


class Appointment(models.Model):
    D_Id=models.ForeignKey(Doctors, on_delete=models.PROTECT,null=True)
    P_Id=models.ForeignKey(Patient_DB, on_delete=models.PROTECT,null=True)
    Date=models.CharField(max_length=10)
    slots=models.IntegerField()

ODA/welcome/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from welcome.models import Doctors

class User_update_Form(forms.ModelForm):

    class Meta:
        model = User
        widgets = {
            'username': forms.TextInput(attrs={})
        }
        fields = ('username', )


class DoctorUpdateForm(forms.ModelForm):
    class Meta:
        model = Doctors
        fields = ('Phone','Desc','doc_type','Degrees','d_website','About_Clinic','Other_info')

ODA/welcome/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.models import User
from welcome.models import Doctors
from welcome.models import Doctors,Patient_DB,Appointment
from patient_home import views
from welcome.decorators import *
from . import forms
from django.core.mail import send_mail



from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context




import os
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from email.mime.image import MIMEImage




doc_type_list = {"doc_list": ['Audiologist ', 'Allergist', 'Andrologists ', 'Anesthesiologist ', 'Cardiologist ',
                              'Cardiovascular Surgeon', 'Clinical Neurophysiologist ', 'Dentist ', 'Dermatologist ',
                              'Emergency Doctors', 'Endocrinologist ', 'Epidemiologists ', 'ENT Specialist ',
                              'Family Practitioner', 'Gastroenterologist ', 'Gynecologist ', 'General Psychiatrist',
                              'Hematologist ', 'Hepatologists ', 'Immunologist ', 'Infectious Disease Specialist',
                              'Internal Medicine Specialists', 'Internists ', 'Medical Geneticist', 'Microbiologist ',
                              'Neonatologist ', 'Nephrologists ', 'Neurologist ', 'Neurosurgeons ', 'Obstetrician ',
                              'Oncologist ', 'Ophthalmologist ', 'Orthopedic Surgeon', 'Orthopedist ', 'Primatologist ',
                              'Parasitologist ', 'Pathologists ', 'Pediatrician ', 'Plastic Surgeon', 'Physiologists ',
                              'Physiatrist ', 'Podiatrists ', 'Psychiatrists ', 'Pulmonologist ', 'Radiologists ',
                              'Reproductive Endocrinologist', 'Urologist ', 'Veterinarian '],
                 "doc_deg": ['MBBS', 'BDS','BHMS', 'BAMS', 'DHMS', 'BUMS', 'BVSc & AH', 'B. Pharm', 'BOT', 'BMLT','BPT',
                            'B.Sc. Nursing', 'BNYS']}



# Create your views here.
# def logout_user(request):
#     if request.user.is_authenticated:
#         logout(request)
#         return redirect('welcome:home')
#     else:
#         return redirect('welcome:home')
@only_doctor
def home(request):
    # pi=request.user.doctors.pk
    # print(pi)
    # lati=Appointment.objects.all().values_list('P_Id','Date','D_Id')
    # arry1=[]
    # arry2=[]
    # print(lati)
    # for i in lati:
    #     if(i[2]==pi):
    #         arry1+=[i[1]]
    #         arry2+=[i[0]]
    # print(arry2)
    # pi=request.user.doctors.T_Id
    # print(pi)
    pi=request.user.doctors.D_Id
    lati=Appointment.objects.all().values_list('P_Id','Date','D_Id','slots')
    arry1=[]
    arry2=[]
    arry2_1=[]
    arry2_2=[]
    arry2_3=[]
    arry3=[]
    k=Doctors.objects.get(pk=pi)
    for i in lati:
        k=Doctors.objects.get(pk=i[2])
        print(i)
        print(type(i[0]))
        if(k.D_Id==pi):
            p=i[1].split('-')
            print(p)
            print(p[0])
            arry2_1+=[p[0]]
            arry2_2+=[p[1]]
            arry2_3+=[p[2]]
            arry3+=[i[3]]
            doc=Patient_DB.objects.get(pk=i[0])
            arry2+=[doc.P_Id.username]
    print(arry2_1)
    print(arry3)
    print(arry1)
    print(arry2)
    return render(request, 'welcome/home.html',{'pat':arry2 , 'year':arry2_1 , 'mon':arry2_2 ,'da':arry2_3,'slo':arry3 })
    # return render(request, 'welcome/home.html',{'lat':zip(arry1,arry2)})

@user_not_auth
def front_page(request):
    return render(request, 'welcome/main_page.html')

@user_not_auth
def doctor_page(request):
    if request.user.is_authenticated:
        try:
            if request.user.doctors.user_pat == 'no':
                return redirect('welcome:home')
        except:
                return redirect('welcome:pat_log')
    return render(request, 'welcome/doc_log.html',doc_type_list)


def doc_login(request):
    if request.method == 'POST':
        email = request.POST.get('doc_email')
        if(User.objects.filter(email=email).exists()):
            password = request.POST.get('doc_pass')
            user = User.objects.filter(email=email).first()

            user = authenticate(username=user.username, password=password)

            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('welcome:home')
                else:
                    return redirect('welcome:home')
            else:
                messages.error(request, f'INVALID EMAIL OR PASSWORD')
                return redirect('welcome:doc-l-r')
        else:
            messages.error(request, f'INVALID EMAIL')
            return redirect('welcome:doc-l-r')

    else:
        raise PermissionDenied


def doc_register(request):
    if request.user.is_authenticated:
        return redirect('welcome:frontpage')
    if request.method == 'POST':
        print("111111")
        firstname = request.POST.get('f_name')
        lastname = request.POST.get('l_name')
        username = firstname + '' + lastname
        email = request.POST.get('email')
        password = request.POST.get('password')
        phone = request.POST.get('phone_num')
        gender = request.POST.get('gender')
        l_num = request.POST.get('license')
        doc_type = request.POST.get('Doctor Type')
        doc_deg = request.POST.get('Doctor_Deg')
        lat = request.POST.get('lat')
        log = request.POST.get('log')

        lat=float(lat);
        long=float(log);
        print(password)
        print(l_num)
        print(phone)
        print(gender)

        if User.objects.filter(email=email).exists():
            return redirect('welcome:home')
        else:
            user = User.objects.create_user(username=username,
                                            email=email,
                                            password=password, )
            d = Doctors(D_Id=user,Phone=phone, license=l_num, gender=gender, Degrees=doc_deg, Latitudes=lat,
                        Longitudes=long, Avail=1,Spec=doc_type)
            d.save()

            htmly = get_template('patient_home/mail2.html')
            html_content=htmly.render()

            msg = EmailMultiAlternatives('Welcome', 'Have a look at what all you can do in ODA', 'onlinedocapp@gmail.com', [email])


            msg.mixed_subtype = 'related'

            for f in ['patient_home/images/ODA-06-06.png']:
                fp = open(os.path.join(os.path.dirname("/Users/KIKKURI/Desktop/asenewpro/ODA-2/ODA/patient_home/static/"), f), 'rb')
                msg_img = MIMEImage(fp.read())
                fp.close()
                msg_img.add_header('Content-ID', '<{}>'.format(f))
                msg.attach(msg_img)

            msg.attach_alternative(html_content, "text/html")
            msg.send()




            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                else:
                    pass
            return redirect('welcome:home')
    return render(request, 'welcome/doc_log.html', doc_type_list)


def pat_log(request):
    if request.user.is_authenticated:
        if User.objects.filter(email=request.user.email).exists():
            name = User.objects.filter(email=request.user.email).first()
            if Doctors.objects.filter(D_Id=name).exists():
                messages.error(request, f'Email already exists try using other email')     ##add in html
                return redirect('welcome:logout')
            else:
                pass
        if request.method == 'POST':
            emergency_email = request.POST.get('emer_email')
            phone = request.POST.get('phone_num')
            em_phone_num=request.POST.get('em_phone_num')
            age = request.POST.get('Age')
            gender = request.POST.get('gender')
            blood_grp = request.POST.get('blood')
            blood_type = request.POST.get('blood_type')
            emer_phone_num = request.POST.get('emer_phone_num')
            Medical = request.POST.get('med_cond')
            blood = blood_grp + ' ' + blood_type
            user = User.objects.filter(email=request.user.email).first()
            # password = 'qwert12345'
            # print('username :')
            # print(user.username)
            # upadate the full name and delataeila

            p = Patient_DB(P_Id=user, Age=age, Gender=gender, Blood_group=blood, Phone_num=phone,emerg_email=emergency_email,
                           Emergency_num=emer_phone_num, medical_con=Medical, user_pat='yes')
            p.save()

            htmly = get_template('patient_home/mail1.html')
            html_content=htmly.render()

            msg = EmailMultiAlternatives('Welcome', 'Have a look at what all you can do in ODA', 'onlinedocapp@gmail.com', [str(request.user.email)])


            msg.mixed_subtype = 'related'

            for f in ['patient_home/images/ODA-05.png']:
                fp = open(os.path.join(os.path.dirname("/Users/KIKKURI/Desktop/asenewpro/ODA-2/ODA/patient_home/static/"), f), 'rb')
                msg_img = MIMEImage(fp.read())
                fp.close()
                msg_img.add_header('Content-ID', '<{}>'.format(f))
                msg.attach(msg_img)

            msg.attach_alternative(html_content, "text/html")
            msg.send()




            return render(request, 'patient_home/home.html')
        else:
            return render(request, 'welcome/pat_log.html')

    return render(request, 'welcome/pat_log.html')


@only_doctor
def pro_upd_doc(request):
    if request.method == 'POST':
        user_form = forms.User_update_Form(request.POST, instance=request.user)

ODA/welcome/templates/welcome/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load static %}
        <link rel="stylesheet" href="{% static 'welcome/base.css' %}">

        <!--Bootstrap	-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!--Google Fonts	-->

        <!-- JQUERY Calendar plugin -->
        <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
        {% block css %} {% endblock %}


    </head>
    <body>
        <!-- Header -->
        <nav class="navbar navbar-expand-lg bg-light navbar-light" id="navbar">
            <div >
                <a class="navbar-brand" href='{% url 'welcome:home' %}' id="ico_logo">
                    &nbsp;
                </a>
            </div>
            <div id="ico_div">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <div id="ico_prof_manage">
                    <a class="nav-link" href ="{% url 'welcome:profile-update' %}">&nbsp;</a>
                  </div>
                </li>
                <li class="nav-item active">
                  <div id="ico_sched">
                    <a class="nav-link" href="{%  url 'welcome:schedule' %}">&nbsp;</a>
                  </div>
                </li>
                <li class="nav-item active">
                  <div id="ico_blog">
                    <a class="nav-link" href="{% url 'blog:blog_home' %}">&nbsp;</a>
                  </div>
                </li>
                <li class="nav-item active">
                  <div id="ico_logout">
                    <a class="nav-link" href="{% url 'welcome:logout' %}">&nbsp;</a>
                  </div>
                </li>
              </ul>
            </div>
        </nav>

        {% block content %} {% endblock %}

        <!-- Footer -->
        <div>
            <footer class="footer-bs">
                <div class="row">
                    <div class="col-md-5 footer-brand animated fadeInLeft">
                        <div id="foot_logo">&nbsp;</div>
                        <p>Made as a project for ‘Applied Software Engineering-1’ course of Indian Institute of Information Technology Sri City under the supervision of Dr. Balasubramanian (Subu) Kandaswamy, Mr. Ravi Venkataraman, Mr. Prabhat Padhay.</p>
                        <p>© 2018 ODA, All rights reserved</p>
                    </div>
                    <div class="col-md-4 footer-nav animated fadeInUp">
                        <div class="col-md-6">
                            <ul class="list">
                                <li><a href="#"><i class="fa fa-user-circle" aria-hidden="true"></i>&nbsp;&nbsp;About Us</a></li>
                                <li><a href="#"><i class="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;Contact</a></li>
                                <li><a href="#"><i class="fa fa-files-o" aria-hidden="true"></i>&nbsp;&nbsp;Documentation</a></li>
                                <li><a href="#"><i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 footer-social animated fadeInDown">
                        <h4>Follow Us</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/sampangi.nikhil" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i>&nbsp;&nbsp;Facebook</a></li>
                            <li><a href="https://twitter.com/sampanginikhil" target="_blank"><i class="fa fa-twitter-square" aria-hidden="true"></i>&nbsp;&nbsp;Twitter</a></li>
                            <li><a href="https://www.instagram.com/7sam_nick99/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i>&nbsp;&nbsp;Instagram</a></li>
                            <li><a href="https://github.com/nikhilsampangi/ODA/" target="_blank"><i class="fa fa-github-square" aria-hidden="true"></i>&nbsp;&nbsp;GitHub</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>
        <!-- Jquery -->
        <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

        <!-- Popper.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

        <!-- Bootstrap -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <!-- Javascript -->
        {% load static %}
        <script src="{% static 'welcome/base.js' %}"></script>

        <!-- Jquery Calendar Plugin -->
        {% load static %}
        <script src="{% static 'welcome/jquery.calendar.js' %}"></script>



    </body>
</html>

ODA/welcome/templates/welcome/loc_win.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>locate</title>
</head>
<body>

</body>
</html>

ODA/welcome/templates/welcome/main_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	  <head>
		<meta charset="utf-8">
		<title>ODA</title>
          <!-- Bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        {% load static %}
		<link rel="stylesheet" href="{% static 'welcome/main_page.css' %}">

        {% load static %}
		<link rel="stylesheet" href="{% static 'welcome/animate.css' %}">

          <!-- Jquery -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
          <!-- Barba.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/barba.js/1.0.0/barba.js" type="text/javascript"></script>

          {% load static %}
		<script type="text/javascript" src="{% static 'welcome/main_page.js' %}"></script>
	  </head>

    <body class="bg">
            <div class="mt1" align="center">
							{% if messages %}
                {% for msg in messages %}
                    {% if msg.tags == 'success' %}
                        <p style="color:green">  {{ msg }}    </p>
                    {% endif %}
                    {% if msg.tags == 'error' %}
                        <p style="color:green">  {{ msg }}    </p>
                    {% endif %}
                {% endfor %}
              {% endif %}
              <table>
                <tr>
                    <div class="animated fadeIn slower">{% load static %}<img class="m1" src="{% static 'welcome/images/ODA-02-01.png' %}" alt="logo"></div>
                </tr>
                <tr>
                  <br>
                  <div class="animated fadeInDown slow delay-1s">
                    <p class="align-middle" id="txt1">You are?</p>
                  </div>
                </tr>
                <tr id="d_row">
                    <td><div class="animated zoomIn delay-2s">
                        <a href="{% url 'welcome:doc-l-r' %}">
                        <button class="btn btn-outline-success" name="doc" value="Doctor" id="doc">Doctor</button>
                        </a>
                    </div></td>
                    <td class="spc"><div class="animated zoomIn delay-2s">or</div></td>
                    <td><div class="animated zoomIn delay-2s">
                        <a href="{% url 'welcome:social:begin' 'google-oauth2' %}">
                        <button class="btn btn-outline-primary" name="pat" value="Patient" id="pat">Patient</button>
                        </a>
                    </div></td>
                </tr>
              </table>
            </div>
    </body>
</html>

ODA/welcome/templates/welcome/pass_reset_complete.html
<html>
        <meta http-equiv="refresh" content="7; url={% url 'welcome:frontpage' %}" />
    <head>
            <title>
                Password Reset
            </title>
    </head>
    <body>
    <p>Your password has be reset </p>
    <p> Please wait few seconds the page is REDIRECTING</p>
    </body>
</html>

ODA/welcome/templates/welcome/password_reset.html
<html>
    <head>
            <title>
                Password Reset
            </title>
    </head>
    <body>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" name="Submit" value="Submit">
        </form>
    </body>
</html>

ODA/welcome/templates/welcome/password_reset_con.html
<html>
    <head>
            <title>
                Password Reset
            </title>
    </head>
    <body>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" >Reset Password</button>
        </form>
    </body>
</html>

ODA/welcome/templates/welcome/password_reset_done.html
<html>
    <meta http-equiv="refresh" content="8; url={% url 'welcome:frontpage'%}" />
    <head>
            <title>
                Password Reset
            </title>
    </head>
    <body>
    <p>  An email has been sent with instructions to reset your password </p>
    <p> Please wait few seconds the page is REDIRECTING</p>
    </body>
</html>