ODA/DandS/urls.py
from django.conf.urls import url
from  . import views

urlpatterns = [
    url(r'^$',views.linking, name='linking'),
    url(r'^search/$',views.search,name="search"),
    url(r'^(?P<body_part>[A-z]+)/$',views.index, name='index'),
    url(r'^(?P<body_part>[A-z]+)/(?P<d_name>[A-z]+)/$', views.info, name='info'),
]

ODA/ODA/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('welcome.urls')),
    path('home/',include('patient_home.urls')),
    path('pharma/', include('Registration.urls')),
    path('pharma/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('Password-Reset/', auth_views.PasswordResetView.as_view(template_name='welcome/password_reset.html'),
         name='password_reset'),
    path('Password-Reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='welcome/password_reset_done.html'),
         name='password_reset_done'),
    path('Password-Reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='welcome/password_reset_con.html'),
         name='password_reset_confirm'),
    path('Password-Reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='welcome/pass_reset_complete.html'),
         name='password_reset_complete'),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ODA/DandS/models.py
from django.db import models

# Create your models here.
class Disease(models.Model):
    disease_name = models.CharField(max_length=255)
    disease_about = models.TextField()
    disease_causes = models.TextField()
    disease_diagnosis = models.TextField()
    disease_treatment = models.TextField()
    disease_part = models.CharField(max_length=20)

    def __self__(self):
        return self.disease_name

class Symptoms(models.Model):
    disease = models.ForeignKey(Disease,on_delete=models.CASCADE)
    symptom = models.TextField()

ODA/DandS/views.py
from django.shortcuts import render
from .models import Disease
from django.http import Http404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.db.models import Q


def linking(request):
    return render(request,'DandS/Linking.html')

def info(request,body_part,d_name):
    try:
        disease = Disease.objects.get(disease_name=d_name)
    except Disease.DoesNotExist:
        raise Http404("Disease not Found")
    return render(request,'DandS/info.html',{'disease':disease})

def index(request,body_part):
    diseases = Disease.objects.filter(disease_part=body_part)
    context = {'diseases': diseases, 'body_part': body_part}
    return render(request, 'DandS/index.html', context)

def search(request):
    if request.method=="POST":
        query = request.POST['search_box']

        if query:
            match = Disease.objects.filter(Q(symptoms__symptom__iexact=query) | Q(disease_name__icontains=query) | Q(disease_part__iexact=query))
            match_unique=list(set(match))

            if match:
                return render(request,'DandS/search.html',{'match_unique':match_unique})
            else:
                messages.error(request,'No results found')
        else:
            return HttpResponseRedirect('.')

    return render(request,'DandS/search.html')

ODA/DandS/templates/DandS/Linking.html
{% extends 'patient_home/base.html' %}

<!Doctype html>
<html>
 <head>
     {% block css %}
        {% load static %}
        <title>Body Parts</title>
        <link rel="stylesheet" href="{% static 'DandS/linking.css' %}">
        <link rel="stylesheet" href="{% static 'DandS/tipped.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Oswald" rel="stylesheet">

     {% endblock %}
 </head>
 <body>

    {% block content %}
        <br><br>
        <!-- Main Content -->
        <div class="container">

            <div class="row">
                <p style="font-family: Josefin Sans;font-size:50px">Select any body part to show diseases linked to it:</p>
            </div>

            <div style="text-align:left; padding-left: 20%;">
                {% load static %}
                <img src="{% static 'DandS/Body.PNG' %}" height="660" width="300" usemap="#parts">
                <map name="parts">
                    <span id="Hand" title="Hand">
                       <area = shape="poly" coords="72,120,47,128,30,160,37,192,22,260,40,308,47,325,47,358,79,380,79,377,70,367,69,354,77,359,77,353,70,337,62,327,63,307,63,293,57,252,67,222,72,194" href="{% url 'index' 'Hand' %}">
                        <area = shape="poly" coords="230,120,255,128,272,160,265,192,280,260,254,327,253,357,237,373,223,375,223,370,230,368,232,353,223,363,224,346,239,322,237,292,246,250,230,210" href="{% url 'index' 'Hand' %}">
                    </span>
                    <span id="Thigh" title="Thigh">
                        <area = shape="poly" coords="80,290,80,455,140,455,150,370,122,360,122,340,100,340" href="{% url 'index' 'Thigh' %}">
                        <area = shape="poly" coords="220,290,220,455,160,455,150,370,178,360,178,340,200,340" href="{% url 'index' 'Thigh' %}">
                    </span>
                    <span id="Leg" title="Leg">
                        <area = shape="poly" coords="88,455,88,473,92,480,92,520,106,583,132,583,130,563,139,502,134,475,139,455" href="{% url 'index' 'Leg' %}">
                        <area = shape="poly" coords="212,455,212,473,208,480,208,520,193,583,167,583,171,563,162,502,167,475,161,455" href="{% url 'index' 'Leg' %}">
                    </span>
                    <span id="Foot" title="Foot">
                        <area = shape="poly" coords="108,583,97,595,82,605,67,610,70,615,82,619,94,620,136,605,132,583" href="{% url 'index' 'Foot' %}">
                        <area = shape="poly" coords="191,583,203,596,219,605,232,610,231,615,219,619,207,620,165,605,168,583" href="{% url 'index' 'Foot' %}">
                    </span>
                    <span id="Brain" title="Brain">
                        <area = shape="circle" coords="150,15,40" href="{% url 'index' 'Brain' %}">
                    </span>
                    <span id="Eye" title="Eye">
                        <area = shape="circle" coords="130,60,6" href="{% url 'index' 'Eye' %}">
                        <area = shape="circle" coords="170,60,6" href="{% url 'index' 'Eye' %}">
                    </span>
                    <span id="Nose" title="Nose">
                        <area = shape="circle" coords="149,70,8" href="{% url 'index' 'Nose' %}">
                    </span>
                    <span id="Ear" title="Ear">
                        <area = shape="poly" coords="120,51,115,51,115,63,120,69" href="{% url 'index' 'Ear' %}">
                        <area = shape="poly" coords="187,51,182,51,182,69,187,63" href="{% url 'index' 'Ear' %}">
                    </span>
                    <span id="Trachea" title="Trachea">
                         <area = shape="rect" coords="143,95,155,145" href="{% url 'index' 'Trachea' %}">
                    </span>
                    <span id="Bronchi" title="Bronchi">
                       <area = shape="poly" coords="154,145,163,150,163,159,149,152,138,159,138,150,144,145" href="{% url 'index' 'Bronchi' %}">
                    </span>
                    <span id="Lung" title="Lung">
                         <area = shape="poly" coords="163,150,163,205,210,230,213,232,218,225,218,175,203,145,181,122,169,123,163,137" href="{% url 'index' 'Lung' %}">
                         <area = shape="poly"  coords="138,150,138,205,92,230,89,232,84,225,84,172,99,145,120,122,133,123,138,137"  href="{% url 'index' 'Lung' %}">
                    </span>
                    <span id="Liver" title="Liver">
                       <area = shape="poly" coords="92,230,87,232,87,255,92,268,108,262,133,255,156,245,159,235,154,222,145,221,135,216,122,216" href="{% url 'index' 'Liver' %}">
                    </span>
                    <span id="Stomach" title="Stomach">
                       <area = shape="poly" coords="181,245,178,255,176,257,166,254,161,251,156,252,151,254,150,260,154,268,162,274,180,277,190,275,205,269,214,253,214,240,206,230,200,229,188,233" href="{% url 'index' 'Stomach' %}">
                   </span>
                   <span id="Oesophagus" title="Oesophagus">
                      <area = shape="poly" coords="188,233,182,220,172,222,172,227,181,245" href="{% url 'index' 'Oesophagus' %}">
                   </span>
                   <span id="Heart" title="Heart">
                       <area = shape="poly" coords="138,175,138,205,133,210,141,220,154,223,169,224,178,213,163,205,163,175" href="{% url 'index' 'Heart' %}">
                   </span>
                   <span id="Mouth" title="Mouth">
                       <area = shape="circle" coords="149,85,6" href="{% url 'index' 'Mouth' %}">
                   </span>
                    <span id="Intestine" title="Intestine">
                        <area = shape="poly" coords="92,278,92,328,212,328,212,278" href="{% url 'index' 'Intestine' %}">
                    </span>
                </map>
            </div>

            <div class="row">
                <p style="font-family: Josefin Sans;font-size:30px">
                    also try:<br>
                    <a href="{% url 'pharma_loc' %}">Pharmacy Locator</a> for finding pharmacies near you and <br>
                    <a href="{% url 'doctor_locator' %}">Doctor Locator</a> for finding doctors near you
                </p>
            </div>
        </div>

        <!-- Jquery -->
        <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

        <!-- Popper.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

        <!-- Bootstrap -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <!-- Javascript -->
        {% load static %}
        <script src="{% static 'DandS/Linking.js' %}"></script>

        <script src="{% static 'Dands/tipped.js' %}"></script>

        <script>
            $(document).ready(function() {
                Tipped.create('#Hand',{ position: 'right'});
                Tipped.create('#Thigh',{ position: 'right'});
                Tipped.create('#Leg',{ position: 'right'});
                Tipped.create('#Foot',{ position: 'right'});
                Tipped.create('#Brain',{ position: 'right'});
                Tipped.create('#Eye',{ position: 'right'});
                Tipped.create('#Nose',{ position: 'right'});
                Tipped.create('#Ear',{ position: 'right'});
                Tipped.create('#Trachea',{ position: 'right'});
                Tipped.create('#Bronchi',{ position: 'right'});
                Tipped.create('#Lung',{ position: 'right'});
                Tipped.create('#Liver',{ position: 'right'});
                Tipped.create('#Stomach',{ position: 'right'});
                Tipped.create('#Oesophagus',{ position: 'right'});
                Tipped.create('#Heart',{ position: 'right'});
                Tipped.create('#Mouth',{ position: 'right'});
                Tipped.create('#Intestine',{ position: 'right'});
            });
        </script>
    {% endblock %}
 </body>
</html>

ODA/DandS/templates/DandS/index.html
{% extends 'patient_home/base.html' %}

<!Doctype html>
<html>
    <head>
        {% block css %}
            <title>Diseases</title>
            <link href="https://fonts.googleapis.com/css?family=Merriweather|Noto+Serif+TC|Titillium+Web" rel="stylesheet">
        {% endblock %}
    </head>
    <body>

        {% block content %}
            <br><br>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        {% if diseases %}
                            <h1 style="font-family: 'Noto Serif TC', serif;"> Diseases related to {{ body_part }} are</h1>
                            <br>
                            <ul class="fa-ul" style="font-family: 'Titillium Web', sans-serif;font-size:20px;">
                              {% for disease in diseases %}
                                  <li>
                                      <i class="fa fa-medkit" aria-hidden="true"></i>&nbsp;
                                      <a href="{% url 'info' body_part disease.disease_name %}">{{ disease.disease_name }}</a>
                                  </li>
                              {% endfor %}
                            </ul>
                        {% else %}
                            <h2>There are no diseases related to this part</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
            <br><br><br><br><br>
        {% endblock %}
    </body>
</html>

ODA/DandS/templates/DandS/info.html
{% extends 'patient_home/base.html' %}

<!Doctype html>
<html>
    <head>
        {% block css %}
            <title>{{ disease.disease_name }}</title>
            <link href="https://fonts.googleapis.com/css?family=Merriweather|Noto+Serif+TC|Titillium+Web" rel="stylesheet">
        {% endblock %}
    </head>

    <body style="font-family: 'Merriweather', serif;">
        {% block content %}
            <br><br><br>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h2 style="font-family: 'Noto Serif TC', serif;">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                            &nbsp;
                            What is {{ disease.disease_name }}?
                        </h2>
                        <br>
                            <p style="margin-left: 30px;">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                &nbsp;
                                {{ disease.disease_about }}
                            </p>
                        <br>
                        <h4 style="font-family: 'Noto Serif TC', serif;">
                            <i class="fa fa-question" aria-hidden="true"></i>
                            &nbsp;
                            Causes:
                        </h4>
                        <br>
                            <p style="margin-left: 30px;">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                &nbsp;
                                {{ disease.disease_causes }}
                            </p>
                        <br>
                        <h4 style="font-family: 'Noto Serif TC', serif;">
                            <i class="fa fa-stethoscope" aria-hidden="true"></i>
                            &nbsp;
                            Diagnosis:
                        </h4>
                        <br>
                            <p style="margin-left: 30px;">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                &nbsp;
                                {{ disease.disease_diagnosis }}
                            </p>
                        <br>
                        <h4 style="font-family: 'Noto Serif TC', serif;">
                            <i class="fa fa-ambulance" aria-hidden="true"></i>
                            &nbsp;
                            Treatment:
                        </h4>
                        <br>
                            <p style="margin-left: 30px;">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                &nbsp;
                                {{ disease.disease_treatment }}
                            </p>
                        <br>
                        <h4 style="font-family: 'Noto Serif TC', serif;">
                            <i class="fa fa-thermometer-full" aria-hidden="true"></i>
                            &nbsp;
                            Symptoms:
                        </h4>
                        <br>
                        <ul class="fa-ul">
                            {% for s in disease.symptoms_set.all %}
                              <li>
                                  <i class="fa fa-caret-right" aria-hidden="true"></i>
                                  &nbsp;
                                  {{ s.symptom }}
                              </li>
                              <br>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endblock %}
    </body>
</html>

ODA/DandS/templates/DandS/search.html
{% extends 'patient_home/base.html'%}

<!Doctype html>

<html>
    <head>
        {% block css %}
        <title>Searchbar</title>
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Oswald" rel="stylesheet">
        {% endblock %}
    </head>
    <body>
        {% block content %}
        <br><br><br>
        <div class="container">
            <div class="row">
                <p style="font-family: Oswald;font-size:40px">Search Diseases, Symptoms or Body parts here....</p>
            </div>
            <br><br>
          <div class="row">
            <div class="col-sm-7" style="margin-left:auto; margin-right:auto;">
              <form action="." method="POST">
                  {% csrf_token %}
                  <input type="text" id="search_box" class="form-control" name="search_box" placeholder="Search Diseases or symptoms...">
                  &nbsp;&nbsp;&nbsp;
                  <button id="search_submit" class="btn btn-outline-primary form-control" type="submit">Search</button>
              </form><br>
              <div style="color:red">
                  {% if messages %}
                          {% for message in messages %}
                              {{ message }}
                          {% endfor %}
                  {% endif %}
              </div>
              <div>
                  {% if match_unique %}
                      <ol>
                          {% for disease in match_unique %}
                              <li style="color:green"><a href="{% url 'info' disease.disease_part disease.disease_name %}">{{ disease.disease_name }}</a></li>
                          {% endfor %}
                      </ol>
                  {% endif %}
              </div>
            </div>
          </div>
        </div>
        <br><br><br><br><br><br><br><br><br>
        {% endblock %}
    </body>
</html>